- hosts: "{{ target_hosts | default('aws') }}"
  become: yes
  become_user: root
  gather_facts: false

  tasks:
    - name: Install python
      raw: dnf install python -y
    - name: install git
      package: 
        name: git
        state: present
    - name: install docker
      package: 
        name: docker
        state: present
    - name: install docker-py
      pip:
        name: docker-py
    - name: install ansible-tower-cli
      pip:
        name: ansible-tower-cli
    - name: install make
      package: 
        name: make
        state: present
    - name: install ansible
      package: 
        name: ansible
        state: present
    - name: pull AWX from git repo
      git:
        repo: https://github.com/ansible/awx
        dest: /awx
        force: yes
        version: 2.1.2
    - name: Start docker daemon
      service:
        name: docker
        enabled: yes
        state: started
    - name: Install libselinux
      package:
        name: libselinux-python
        state: present
    - name: Change value of host key checking on AWX server
      lineinfile:
        path: /etc/ansible/ansible.cfg
        regexp: '#host_key_checking = False'
        line: 'host_key_checking = False' 
    - name: generate ssh key for local use
      command: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
      args:
        creates: /root/.ssh/id_rsa
    - name: configure local ssh access
      copy: 
        remote_src: True 
        src: /root/.ssh/id_rsa.pub
        dest: /root/.ssh/authorized_keys
    - name: Add local key to authorized_keys
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    - name: change value of host in installer inventory
      lineinfile:
        path: /awx/installer/inventory
        regexp: 'localhost ansible_connection=local ansible_python_interpreter="/usr/bin/env python"'
        line: 'localhost'
    - name: install AWX
      command:  ansible-playbook -i /awx/installer/inventory /awx/installer/install.yml 
    - name: Configure tower-cli
      shell: "{{ item }}" 
      with_items:
        - tower-cli config verify_ssl false
        - tower-cli config username admin
        - tower-cli config password password
        - tower-cli config host http://127.0.0.1
    - name: Check to ensure AWX has come up successfully - this can take some time.
      shell: tower-cli project list
      register: result
      until: result.stdout.find("Demo Project") != -1
      retries: 10
      delay: 30
    - name: copy tower config file to node
      copy:
        src: files/setup-tower.sh
        dest: /root/setup-tower.sh
        mode: 0755 
    - name: copy workflow schema file to node
      copy:
        src: files/pacman_workflow.yml
        dest: /root/pacman_workflow.yml
        mode: 0755 
    - name: Run tower setup script
      shell: /root/setup-tower.sh
