- hosts: "{{ target_hosts | default('null-hosts') }}"
  connection: local
  vars:
    device_info:
      host: "{{ inventory_hostname }}"
      username: admin
      password: password
      authorize: yes
      auth_pass: password
  tasks: 
    - name: create object group
      asa_config:
        lines:
          - range 192.168.100.0 192.168.100.255
        parents: ['object network inside-net']
        provider: "{{ device_info }}"
      register: result
    - debug: var=result
    - name: add ACL on outside interface
      asa_acl:
        lines: 
          - access-list outside-in extended permit ip any object inside-net

        provider: "{{ device_info }}"

