- hosts: "{{ target_hosts | default('null-hosts') }}"
  connection: local
  vars:
    credentials:
      host: "{{ inventory_hostname }}"
      username: cisco
      password: cisco

  roles: 
   - cisco-3750
