- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: Spin up a container
    docker_container:
     name: "container{{ item }}"
     image: scottorama1/eap7
     state: started
    with_sequence: count=2
  - name: get container IP
    shell: ips
    register: output_var
  - debug: var=output_var.stdout_lines
