- hosts: "csr1000v"
  connection: local
  vars:
    device_info:
      host: "{{ inventory_hostname }}"
      username: svk
      password: Codecowboy123
     # authorize: yes
      #auth_pass: password
      #transport: cli
      timeout: 60
#    interface_up: "{{ interface_up }}"
#  tasks: 
#    - name: Bring up secondary interface
#      ios_config:
#        parents: "interface GigabitEthernet2"
#        lines: 
#          - no shutdown
#          - ip address dhcp
#        provider: "{{ device_info }}"
#      when: interface_up == 'true'
    - name: configure the login banner
      ios_banner:
        banner: login
        text: |
         ------------------------------------------
         This banner was set by Ansible
         ....tell me this doesn't remove drudgery
         ------------------------------------------
        state: present
        provider: "{{ device_info }}"
       when: banner == 'true'
    - name: configure the login banner
      ios_banner:
        #banner: login
        state: absent
        provider: "{{ device_info }}"
      when: banner == 'false'
