- hosts: "csr1000v"
  connection: local
  vars:
    device_info:
      host: "{{ inventory_hostname }}"
      username: codecowboy
      password: Codecowboy12
     # authorize: yes
      #auth_pass: password
      transport: cli
      timeout: 30
  tasks: 
    - name: Bring up secondary interface
      ios_config:
        parents: "interface GigabitEthernet2"
        lines: 
          - shutdown
          - no ip address
        provider: "{{ device_info }}"
      register: result
#    - debug: var=result
    - name: configure the login banner
      ios_banner:
        banner: login
        text: |
         ------------------------------------------
         This banner was set by Ansible
         ....tell me this doesn't remove drudgery
         ------------------------------------------
        state: present
        provider: "{{ device_info }}"
#    - name: configure the login banner
#      ios_banner:
#        banner: login
#        state: absent
#        provider: "{{ device_info }}"
