- name: Base VE config
  hosts: "{{ target_hosts | default('f5') }}"
  connection: local
  gather_facts: False

  vars:
    bigip_provider:
      server: 10.1.1.245
      user: admin
      password: admin
      validate_certs: no

  tasks:
  - name: Create pool
    bigip_pool:
      state: present
      name: "{{ item.name }}"
      partition: Common
      lb_method: "{{ item.lb_method }}"
      monitors:
        - http
      provider: "{{ bigip_provider }}"
    with_items:
      - name: pool1
        lb_method: round-robin
      - name: pool2
        lb_method: round-robin
      - name: pool3
        lb_method: round-robin
    delegate_to: localhost
  - name: Add pool member
    bigip_pool_member:
      state: present
      pool: "{{ item.bigip_pool }}"
      partition: Common
      host: "{{ item.bigip_pool_member }}"
      port: "{{ item.bigip_pool_member_port }}"
      provider: "{{ bigip_provider }}"
    delegate_to: localhost
    with_items:
      - bigip_pool: pool1
        bigip_pool_member: 1.1.1.1
        bigip_pool_member_port: 80
      - bigip_pool: pool1
        bigip_pool_member: 1.1.1.2
        bigip_pool_member_port: 80
      - bigip_pool: pool1
        bigip_pool_member: 1.1.1.3
        bigip_pool_member_port: 80
      - bigip_pool: pool2
        bigip_pool_member: 2.2.2.1
        bigip_pool_member_port: 80
      - bigip_pool: pool2
        bigip_pool_member: 2.2.2.2
        bigip_pool_member_port: 80
      - bigip_pool: pool2
        bigip_pool_member: 2.2.2.3
        bigip_pool_member_port: 80
      - bigip_pool: pool3
        bigip_pool_member: 3.3.3.1
        bigip_pool_member_port: 80
      - bigip_pool: pool3
        bigip_pool_member: 3.3.3.2
        bigip_pool_member_port: 80
      - bigip_pool: pool3
        bigip_pool_member: 3.3.3.3
        bigip_pool_member_port: 80
  - name: Add virtual server
    bigip_virtual_server:
      state: present
      partition: Common
      name: "{{ item.bigip_virtual_name }}"
      destination: "{{ item.bigip_virtual_destination }}"
      port: "{{ item.bigip_vip_port }}"
      pool: "{{ item.bigip_pool }}"
      snat: "{{ item.bigip_virtual_snat_type }}"
      description: "{{ item.bigip_virtual_description }}"
      provider: "{{ bigip_provider }}"
    delegate_to: localhost
    with_items:
      - bigip_virtual_name: virt1
        bigip_virtual_destination: 100.1.1.1
        bigip_vip_port: 80
        bigip_pool: pool1
        bigip_virtual_snat_type: automap
        bigip_virtual_description: "Test VIP"
      - bigip_virtual_name: virt2
        bigip_virtual_destination: 200.1.1.1
        bigip_vip_port: 80
        bigip_pool: pool2
        bigip_virtual_snat_type: automap
        bigip_virtual_description: "Test VIP 2"
      - bigip_virtual_name: virt3
        bigip_virtual_destination: 233.1.1.1
        bigip_vip_port: 80
        bigip_pool: pool2
        bigip_virtual_snat_type: automap
        bigip_virtual_description: "Test VIP 3"
        
