- hosts: "{{ target_hosts | default('aws') }}"
  become: yes
  become_user: root
  connection: local

  vars:
    api_url: 'api.cloudservices.f5.com'
    api_version: v1
    password: 'somepassword'
    username: 'someusername'


  tasks:
    - name: login to cloud services
      uri:
        url: https://{{ api_url }}/{{ api_version }}/svc-auth/login
        body: {"username":"{{ username }}","password":"{{ password }}"}
        method: POST
        body_format: json
      delegate_to: localhost
      register: cloud_access_token
    - debug: var=cloud_access_token.json.access_token
    - name: get account details
      uri:
        url: https://{{ api_url }}/{{ api_version }}/svc-account/user
        headers: 
          Authorization: 'Bearer {{ cloud_access_token.json.access_token }}'
        method: GET
        body_format: json
      delegate_to: localhost
      register: user_info
    - debug: var=user_info.json.id
    - name: get subscriptions
      uri:
        url: https://{{ api_url }}/{{ api_version }}/svc-subscription/subscriptions?account_id={{ user_info.json.primary_account_id }}
        headers: 
          Authorization: 'Bearer {{ cloud_access_token.json.access_token }}'
        method: GET
        body_format: json
      delegate_to: localhost
      register: subscription_info
    - debug: var=subscription_info
    - name: get catalogue items
      uri:
        url: https://{{ api_url }}/{{ api_version }}/svc-catalog/catalogs
        headers: 
          Authorization: 'Bearer {{ cloud_access_token.json.access_token }}'
        method: GET
        body_format: json
      delegate_to: localhost
      register: catalogue_info
    - debug: var=catalogue_info.json.Catalogs
    - name: do stuf
      debug:
        msg: "Item={{ item }} Key={{ item.key }} value={{ item.value }}"
      with_dict: "{{ catalogue_info.json.Catalogs }}"
      when: (item.key  == 'name' and item.value == 'DNS') 
    - name: do stuf
      debug:
        msg: "{{ catalogue_info.json.Catalogs | json_query(query) }}"
      vars: 
        query: "[].name"
    - name: do stuf
      debug:
        msg: "{{ catalogue_info.json.Catalogs | json_query(query) }}"
      vars: 
        query: "[].{name: name, catalog_id: catalog_id}"
    - name: do stuf
      debug:
        msg: "{{ catalogue_info.json.Catalogs | json_query(query) }}"
      vars: 
        query: "[].{name: name, catalog_id: catalog_id} | [?name=='DNS']"
