- hosts: jenkins
  gather_facts: yes
  tasks:
  - name: Kick off Jenkins Job
    uri: 
      url: "http://52.62.219.222:8080/job/AS3-deploy/build?token=fooble"
      method: POST
      user: admin
      password: password
      force_basic_auth: yes
      status_code: 201
    delegate_to: 127.0.0.1
