- name: Provision ec2 instances based on the environment
  hosts: localhost
  connection: local
  gather_facts: True

  tasks:
    - name: Print some debug information 
      vars: 
        msg: |
            Module Variables ("vars"):
            --------------------------------
            {{ vars | to_nice_json }} 
 
            Environment Variables ("environment"):
            --------------------------------
            {{ environment | to_nice_json }} 
 
            GROUP NAMES Variables ("group_names"):
            --------------------------------
            {{ group_names | to_nice_json }}
 
            GROUPS Variables ("groups"):
            --------------------------------
            {{ groups | to_nice_json }}
 
            HOST Variables ("hostvars"):
            --------------------------------
            {{ hostvars | to_nice_json }} 
    - name: Get instance tags
      ec2_tag:
        region: ap-southeast-2
        resource: "{{ ansible_facts['ec2_id'] }}"
        state: present
        tags:
          Name: dbserver
          Env: production
