- name: Provision ec2 instances based on the environment
  hosts: all
  #connection: local
  gather_facts: True

  vars:
    fooble: "{{ ec2_id }}"

  tasks:
  - name: get variables
    debug: var=fooble 
