- name: Provision ec2 instances based on the environment
  hosts: localhost
  connection: local
  gather_facts: True

  vars:
    fooble: "{{ hostvars['ec2_id'] }}"

  tasks:
  - name: get variables
    debug:
      var: hostvars[inventory_hostname]
