- hosts: "{{ target_hosts | default('aws') }}"
  become: yes
  become_user: root

  vars:
    #zone_name: "svkcode.org"


  tasks:
    - name: Check all vars are present
      assert:
        that:
          - zone_name != ""
    - name: Install bind and bind utils fedoraish
      package: 
        name: "{{ item }}"
        state: present
      with_items:
        - bind
        - bind-utils
      when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'
    - name: Install bind and bind utils debianish
      package: 
        name: "{{ item }}"
        state: present
      with_items:
        - bind9
      when: ansible_pkg_mgr == 'apt'
    - name: Update json blob
      template:
        src: primary_dns.j2
        dest: primary_dns.db
      delegate_to: localhost
    - name: Update gslb zone file
      template:
        src: gslb.j2
        dest: gslb.db
      delegate_to: localhost
    - name: Copy file with owner and permissions
      copy:
        src: ./primary_dns.db
        dest: /var/named/primary_dns.db
        owner: root
        group: named
        mode: 0640
    - name: Copy gslb zone file into place
      copy:
        src: ./gslb.db
        dest: /var/named/gslb.db
        owner: root
        group: named
        mode: 0640
    - name: Updated named.conf
      blockinfile:
        path: /etc/named.conf
        block: |
          zone "{{ zone_name }}" IN {
            type master;
            file "primary_dns.db";
          };
          zone "gslb.{{ zone_name }}" IN {
            type master;
            file "gslb.db";
          };
    - name: Update bind options
      lineinfile:
        path: /etc/named.conf
        insertafter: 'allow-query     { localhost; };'
        line: 'allow-transfer { any; };'
    - name: Update bind options
      lineinfile:
        path: /etc/named.conf
        regexp: 'allow-query     { localhost; };'
        line: 'allow-query { any; };'
    - name: Update bind options
      lineinfile:
        path: /etc/named.conf
        regexp: 'listen-on port 53 { 127.0.0.1; };'
        line: 'listen-on port 53 { any; };'
    - name: Start named daemon
      service:
        name: named
        enabled: yes
        state: started

