- hosts: all
  become: yes
  become_user: root
  gather_facts: True 

  tasks:
    - name: install httpd
      dnf:
        name: httpd
        state: present
    - set_fact: 
        apache: groovy
    - setup:
