- hosts: all
  become: yes
  become_user: root
  gather_facts: true 

  tasks:
    - name: install httpd
      package:
        name: httpd
        state: present
    - set_fact: 
        apache: groovy
      
