- name: Provision ec2 instances based on the environment
  hosts: "{{ target_hosts | default('none') }}"
  connection: local
  gather_facts: True

  vars_files:
#    - roles/ec2/vars/aws_creds.yml

  tasks:
  - name: Terminate instances
    ec2:
#      ec2_access_key: "{{ ec2_access_key }}"
#      ec2_secret_key: "{{ ec2_secret_key }}"
      region: ap-southeast-2
      instance_ids: "{{ ec2_id }}"
      state: absent
      wait: true
    register: ec2
