- hosts: "{{ target_hosts | default('eap-hosts') }}"
  vars:
    - new_dir: /foo
  become: yes
  become_user: root
  tasks:
    - name: Install git
      package: 
        name: git
        state: present
    - name: Install java jdk
      package: 
        name: java-1.8.0-openjdk-devel
        state: present
    - name: Install tomcat
      package: 
        name: tomcat
        state: present
    - name: pull hello world from git
      git:
        repo: git://github.com/svkdotcloud/helloworld-java
        dest: "{{ new_dir }}"
        clone: yes
    - name: compile war file
      shell:  ./build.sh chdir={{ new_dir }}
    - name: Copy file to deployment directory
      shell: cp /helloworld.war /usr/share/tomcat/webapps
    - name: Turn off firewalld
      systemd:
        name: firewalld
        state: stopped
    - name: Start Tomcat
      systemd:
        name: tomcat
        state: started
#    - name: foo
#      shell: echo foo
