- hosts: "{{ target_hosts | default('eap-hosts') }}"
  become: yes
  become_user: root
  tasks:
    - name: Install git
      package: 
        name: git
        state: present
    - name: Install java jdk
      package: 
        name: java-1.8.0-openjdk-devel
        state: present
    - name: Install tomcat
      package: 
        name: tomcat
        state: present
    - name: Start Tomcat
      systemd:
        name: tomcat
        state: started
