- hosts: "{{ target_hosts | default('eap-hosts') }}"
  tasks:
    - name: install tomcat
      win_chocolatey: 
        name: tomcat
        state: present
    - name: deploy war file
      win_copy:
        src: /home/svankalk/Desktop/sa_data_demo.war
        dest: C:\Program Files\Apache Software Foundation\tomcat\apache-tomcat-8.5.12\webapps\sa_data_demo.war
        #dest: c:\foo\sa_data_demo.war
