- name: Install Git
  yum: 
     name: git 
     state: latest
- name: Install Development Tools
  yum: 
     name: "@Development Tools"
     state: latest
- name: git pull
  git:
     repo: git://github.com/svkdotcloud/listener
     dest: /dest/
     clone: yes
- name: compile code
  shell: make 
  args:
    chdir: /dest/

