- name: Install selinux bindings
  package:
    name: libselinux-python
    state: present
- name: Install java
  package:
    name: java-openjdk-devel
    state: present
- name: Install git
  package:
    name: git
    state: present
- name: Install Development Tools
  package:
    name: "@Development Tools"
    state: present
- name: Install c++
  package:
    name: gcc-c++
    state: present
- name: Pull kafka code from mirror
  get_url: url=http://www.mirrorservice.org/sites/ftp.apache.org/kafka/{{ kafka_version }}/kafka_2.12-{{ kafka_version }}.tgz dest=/tmp/kafka_2.12-{{ kafka_version }}.tar.gz mode=0644 force=no
