- include_tasks: fedora_package.yml
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'
- include_tasks: apt_package.yml
  when: ansible_pkg_mgr == 'apt'
- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: /tmp/kafka_2.12-{{ kafka_version }}.tar.gz
    dest: /tmp/
    remote_src: yes
- name: download kafkacat
  git:
    repo: git://github.com/edenhill/kafkacat
    dest: /tmp/kafkacat
    clone: yes

