- hosts: localhost
  connection: local
  vars:
    credentials:
      host: 192.168.100.108
      username: cisco
      password: cisco
  tasks:
    - name: test IOS Command
      register: command_out
      ios_command:
        commands: "show version"
        provider: "{{ credentials }}"
