- hosts: cisco
  connection: local
  vars:
    credentials:
      host: "{{ inventory_hostname }}"
      username: cisco
      password: cisco
  tasks:
    - name: test IOS Command
      ios_command:
        commands: "show version"
        provider: "{{ credentials }}"
      register: version
    - debug: var=version.stdout_lines

