- include: yum_package.yml
- name: Turn off firewalld
  systemd:
    name: firewalld
    state: stopped 
- copy: 
    src: files/jboss-eap-7.0.0.zip
    dest: /opt/eap7/
    owner: root
    group: root
    mode: 0644
- name: unzip EAP
  shell: unzip -o jboss-eap-7.0.0.zip chdir=/opt/eap7/
- name: Add management user
  shell: /opt/eap7/jboss-eap-7.0/bin/add-user.sh admin Password123# --silent
- name: copy startup file to server
  copy: 
    src: files/start.sh
    dest: /root/start.sh
    owner: root
    group: root
    mode: 0755
- name: copy systemd file in to place
  copy:
    src: files/jboss-as-standalone.service
    dest: /etc/systemd/system/jboss-as-standalone.service
    owner: root
    group: root
    mode: 0644
- name: add EAP admin user
  shell: /opt/eap7/jboss-eap-7.0/bin/add-user.sh admin Password123# --silent
- name: Systemd reload
  systemd: 
    daemon_reload: yes
    name: jboss-as-standalone.service
    enabled: yes
    state: started
- name: Wait for JBoss to start up
  wait_for: 
    port: 9990
