- name: Install selinux-python bindings
  package:
    name: libselinux-python
    state: present
- name: Install unzip
  package:
    name: unzip
    state: present
- name: Install java
  package:
    name: java-1.8.0-openjdk-devel
    state: present
