nightwatch_dir: "/nightwatch"
selenium_file: "selenium-server-standalone-3.9.1.jar"
chromedriver_file: "chromedriver"
nightwatch_config_file: "nightwatch.json"
nightwatch_user: "jenkins"
nightwatch_group: "jenkins"


